#!/usr/bin/env python3
"""Generate comprehensive PDF report from markdown documents and pipeline results."""

import json
import os
import sys
from pathlib import Path

# Try to import weasyprint; if not available, fallback to reportlab
HAVE_WEASYPRINT = False
HAVE_REPORTLAB = False
try:
    import weasyprint
    HAVE_WEASYPRINT = True
except ImportError:
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import mm
        HAVE_REPORTLAB = True
    except ImportError:
        pass

def load_markdown_files(docs_dir: str = "docs") -> dict:
    """Load all .md files from docs directory."""
    md_files = {}
    docs_path = Path(docs_dir)
    if not docs_path.exists():
        print(f"Warning: docs directory '{docs_dir}' not found.")
        return md_files
    for f in sorted(docs_path.glob("*.md")):
        try:
            md_files[f.stem] = f.read_text(encoding="utf-8")
        except Exception as e:
            print(f"Error reading {f}: {e}")
    return md_files

def load_pipeline_results(results_file: str = "data/model_performance_log.json") -> dict:
    """Load pipeline results from JSON file."""
    results_path = Path(results_file)
    if not results_path.exists():
        print(f"Warning: pipeline results file '{results_file}' not found.")
        return {}
    try:
        with open(results_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        print(f"Error reading {results_file}: {e}")
        return {}

def build_html_report(md_files: dict, pipeline_results: dict) -> str:
    """Build an HTML string from markdown content and pipeline results."""
    # Simple markdown to HTML conversion (basic)
    def md_to_html(text: str) -> str:
        lines = text.split('\n')
        html_lines = []
        in_code = False
        for line in lines:
            if line.startswith('```'):
                if in_code:
                    html_lines.append('</code></pre>')
                    in_code = False
                else:
                    html_lines.append('<pre><code>')
                    in_code = True
                continue
            if in_code:
                html_lines.append(line)
                continue
            if line.startswith('# '):
                html_lines.append(f'<h1>{line[2:]}</h1>')
            elif line.startswith('## '):
                html_lines.append(f'<h2>{line[3:]}</h2>')
            elif line.startswith('### '):
                html_lines.append(f'<h3>{line[4:]}</h3>')
            elif line.startswith('- '):
                html_lines.append(f'<li>{line[2:]}</li>')
            elif line.strip() == '':
                html_lines.append('<br/>')
            else:
                html_lines.append(f'<p>{line}</p>')
        return '\n'.join(html_lines)

    html_parts = ['<html><head><meta charset="utf-8"><title>Comprehensive Report</title></head><body>']
    html_parts.append('<h1>Comprehensive Report: Room Temperature Superconductors</h1>')
    html_parts.append('<p>Generated by generate_report.py</p>')
    html_parts.append('<hr/>')

    # Add markdown sections
    for name, content in md_files.items():
        html_parts.append(f'<h2>Section: {name}</h2>')
        html_parts.append(md_to_html(content))
        html_parts.append('<hr/>')

    # Add pipeline results
    if pipeline_results:
        html_parts.append('<h2>Pipeline Results</h2>')
        html_parts.append('<pre>' + json.dumps(pipeline_results, indent=2) + '</pre>')
    else:
        html_parts.append('<p>No pipeline results available.</p>')

    html_parts.append('</body></html>')
    return '\n'.join(html_parts)

def generate_pdf_weasyprint(html: str, output_path: str):
    """Generate PDF using weasyprint."""
    doc = weasyprint.HTML(string=html)
    doc.write_pdf(output_path)
    print(f"PDF report generated: {output_path}")

def generate_pdf_reportlab(html: str, output_path: str):
    """Fallback PDF generation using reportlab (simple text extraction)."""
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.lib.pagesizes import A4
    import re

    doc = SimpleDocTemplate(output_path, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    # Simple HTML tag stripping for reportlab
    def strip_html(text):
        return re.sub(r'<[^>]+>', '', text)

    # Split HTML into lines and convert
    lines = html.split('\n')
    for line in lines:
        stripped = strip_html(line).strip()
        if not stripped:
            continue
        if line.startswith('<h1>'):
            story.append(Paragraph(stripped, styles['Title']))
        elif line.startswith('<h2>'):
            story.append(Paragraph(stripped, styles['Heading2']))
        elif line.startswith('<h3>'):
            story.append(Paragraph(stripped, styles['Heading3']))
        elif line.startswith('<li>'):
            story.append(Paragraph('• ' + stripped, styles['Normal']))
        elif line.startswith('<pre>'):
            story.append(Paragraph(stripped, styles['Code']))
        else:
            story.append(Paragraph(stripped, styles['Normal']))
        story.append(Spacer(1, 2*mm))

    doc.build(story)
    print(f"PDF report generated (reportlab fallback): {output_path}")

def main():
    if len(sys.argv) > 1:
        output_path = sys.argv[1]
    else:
        output_path = "report.pdf"

    md_files = load_markdown_files()
    pipeline_results = load_pipeline_results()

    if not md_files and not pipeline_results:
        print("No markdown files or pipeline results found. Nothing to generate.")
        sys.exit(1)

    html = build_html_report(md_files, pipeline_results)

    if HAVE_WEASYPRINT:
        generate_pdf_weasyprint(html, output_path)
    elif HAVE_REPORTLAB:
        generate_pdf_reportlab(html, output_path)
    else:
        print("Error: Neither weasyprint nor reportlab installed. Install one of them.")
        print("  pip install weasyprint  or  pip install reportlab")
        sys.exit(1)

if __name__ == "__main__":
    main()
